name: Docker Build and Push

on:
  push:
    branches:
      - dev  # Adjust this to match your branch name

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
        
    - name: Build Docker image
      run: docker build -t careerforge:latest .
      
